export enum DashboardWidgetId {
    TOTAL_DELIVERIES = 1,
    SLA_COMPLIANCE = 2,
    AVG_DELIVERY_TIME = 3,
    ACTIVE_HUBS = 4,
    DELIVERIES_OVER_TIME = 5,
    REGION_SLA = 6,
    AGENT_ACTIVITY = 7,
    REVENUE_VS_COST = 8,
    DELIVERY_STATUS = 9,
    FLEET_UTILIZATION = 10,
}

